[workspace.package]
version = "0.0.1"
authors = ["Project AIRI"]
edition = "2024"
rust-version = "1.80"
readme = "README.md"
homepage = "https://github.com/proj-airi/candle-examples"
repository = "https://github.com/proj-airi/candle-examples"
license = "MIT"
publish = false

[workspace]
resolver = "3"
members = [
    "apps/candle-example-whisper-mic",
    "apps/candle-example-silero-vad",
]
