version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AIRI
  - byteorder
  - clippy
  - coreml
  - cuda
  - directml
  - distil
  - dtolnay
  - DTYPE
  - gguf
  - huggingface
  - logits
  - logprob
  - melfilters
  - mmaped
  - ndarray
  - onnx
  - probs
  - Resampler
  - rngs
  - safetensors
  - Seedable
  - serde
  - silero
  - snac
  - softmax
  - unsqueeze
ignoreWords: []
import: []
