[workspace]
authors = ["Neko Ayaka <neko@ayaka.moe>"]
channels = ["conda-forge"]
name = "candle-examples"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
pip = ">=25.1.1,<26"

[pypi-dependencies]
setuptools = ">=80.9.0, <81"
numpy = "==2.2"
huggingface-hub = ">=0.33.2, <0.34"
transformers = ">=4.53.1, <5"
onnxruntime = ">=1.22.0, <2"
torch = ">=2.7.1, <3"
torchaudio = ">=2.7.1, <3"
torchvision = ">=0.22.1, <0.23"
matplotlib = ">=3.10.3, <4"
librosa = { git = "https://github.com/librosa/librosa" }
